MVC/RoleTopMVC/Models/ErrorViewModel.cs
using System;

namespace RoleTopMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVC/RoleTopMVC/Controllers/EventosController.cs
using Microsoft.AspNetCore.Mvc;

namespace RoleTopMVC.Controllers
{
    public class EventosController : Controller
    {
        public IActionResult Shows()
        {
            return View();
        }
    }
}

MVC/RoleTopMVC/Controllers/GaleriaController.cs
using Microsoft.AspNetCore.Mvc;

namespace RoleTopMVC.Controllers
{
    public class GaleriaController : Controller
    {
        public IActionResult Fotos()
        {
            return View();
        }
    }
}

MVC/RoleTopMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RoleTopMVC.Models;

namespace RoleTopMVC.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVC/RoleTopMVC/Views/Eventos/Shows.cshtml
<main>
        
        <div class="eventos">
            <div class="evento1">
                <h2><strong>Show do Grupo Revelação</strong></h2>
                <h3>17 AGO 2019</h3>
                <p>Sáb - 22:00</p>
                <p>Venha curtir o show do grupo de pagode mais querido do Brasil.</p>
            </div>
            <div class="evento2">
                <h2><strong>Evento - Empresa Bradesco</strong></h2>
                <h3>23 AGO 2019</h3>
                <p>Sex - 18:00</p>
                <p>Confraternização do Banco Bradesco por atingir os resultados trimestrais.</p>
            </div>
            <div class="evento3">
                <h2><strong>Festa Kids</strong></h2>
                <h3>7 SET 2019</h3>
                <p>Sáb - 12:00</p>
                <p>Festa dedicada as crianças, com muitas brincadeiras, gincanas e comidas.</p>
            </div>
        </div>

    </main>

MVC/RoleTopMVC/Views/Galeria/Fotos.cshtml
<main>
            <section id="eventos">
                <h2><strong><u>Eventos Corporativos</u></strong></h2>
                <ul id="imgs">
                    <li><a href="#ev-corp1"><img src="img/eventos_corporativos/1.jpg" alt="Evento empresa Vigor" class="min"></a></li>
                    <li><a href="#ev-corp2"><img src="img/eventos_corporativos/2.jpg" alt="Evento empresa Gurlo" class="min"></a></li>
                    <li><a href="#ev-corp3"><img src="img/eventos_corporativos/3.jpg" alt="Evento empresa Bradesco" class="min"></a></li>
                    <li><a href="#ev-corp4"><img src="img/eventos_corporativos/4.jpg" alt="Evento empresa Roca" class="min"></a></li>
                </ul>
                
                <div class="lbox" id="ev-corp1">
                    <div class="box-img">
                        <a href="#ev-corp4" class="btn" id="prev">&#171;</a>
                        <a href="" class="btn" id="close">X</a>
                        <img src="img/eventos_corporativos/1.jpg" alt="Evento empresa Vigor">
                        <a href="#ev-corp2" class="btn" id="next">&#187;</a>
                    </div>
                </div>

                <div class="lbox" id="ev-corp2">
                    <div class="box-img">
                        <a href="#ev-corp1" class="btn" id="prev">&#171;</a>
                        <a href="" class="btn" id="close">X</a>
                        <img src="img/eventos_corporativos/2.jpg" alt="Evento empresa Gurlo">
                        <a href="#ev-corp3" class="btn" id="next">&#187;</a>
                    </div>
                </div>

                <div class="lbox" id="ev-corp3">
                    <div class="box-img">
                        <a href="#ev-corp2" class="btn" id="prev">&#171;</a>
                        <a href="" class="btn" id="close">X</a>
                        <img src="img/eventos_corporativos/3.jpg" alt="Evento empresa Bradesco">
                        <a href="#ev-corp4" class="btn" id="next">&#187;</a>
                    </div>
                </div>

                <div class="lbox" id="ev-corp4">
                    <div class="box-img">
                        <a href="#ev-corp3" class="btn" id="prev">&#171;</a>
                        <a href="" class="btn" id="close">X</a>
                        <img src="img/eventos_corporativos/4.jpg" alt="Evento empresa Roca">
                        <a href="#ev-corp1" class="btn" id="next">&#187;</a>
                    </div>
                </div>
            </section>

            <section id="festas">
                    <h2><strong><u>Festas e Shows</u></strong></h2>
                    <ul id="imgs">
                        <li><a href="#festa1"><img src="img/Festas_shows/1.jpeg" alt="Festa" class="min"></a></li>
                        <li><a href="#festa2"><img src="img/Festas_shows/2.jpg" alt="Balada" class="min"></a></li>
                        <li><a href="#festa3"><img src="img/Festas_shows/3.jpg" alt="Show do Grupo Revelação" class="min"></a></li>
                        <li><a href="#festa4"><img src="img/Festas_shows/4.jpg" alt="Show" class="min"></a></li>
                    </ul>
                    
                    <div class="lbox" id="festa1">
                        <div class="box-img">
                            <a href="#festa4" class="btn" id="prev">&#171;</a>
                            <a href="" class="btn" id="close">X</a>
                            <img src="img/Festas_shows/1.jpeg" alt="Festa">
                            <a href="#festa2" class="btn" id="next">&#187;</a>
                        </div>
                    </div>
    
                    <div class="lbox" id="festa2">
                        <div class="box-img">
                            <a href="#festa1" class="btn" id="prev">&#171;</a>
                            <a href="" class="btn" id="close">X</a>
                            <img src="img/Festas_shows/2.jpg" alt="Balada">
                            <a href="#festa3" class="btn" id="next">&#187;</a>
                        </div>
                    </div>
    
                    <div class="lbox" id="festa3">
                        <div class="box-img">
                            <a href="#festa2" class="btn" id="prev">&#171;</a>
                            <a href="" class="btn" id="close">X</a>
                            <img src="img/Festas_shows/3.jpg" alt="Show do Grupo Revelação">
                            <a href="#festa4" class="btn" id="next">&#187;</a>
                        </div>
                    </div>
    
                    <div class="lbox" id="festa4">
                        <div class="box-img">
                            <a href="#festa3" class="btn" id="prev">&#171;</a>
                            <a href="" class="btn" id="close">X</a>
                            <img src="img/Festas_shows/4.jpg" alt="Show">
                            <a href="#festa1" class="btn" id="next">&#187;</a>
                        </div>
                    </div>
                </section>

                <section id="formaturas">
                        <h2><strong><u>Formaturas e Casamentos</u></strong></h2>
                        <ul id="imgs">
                            <li><a href="#format1"><img src="img/form_casa/1.jpg" alt="Festa de Formatura" class="min"></a></li>
                            <li><a href="#format2"><img src="img/form_casa/2.jpg" alt="Festa de Formatura" class="min"></a></li>
                            <li><a href="#format3"><img src="img/form_casa/3.jpg" alt="Festa de Casamento" class="min"></a></li>
                            <li><a href="#format4"><img src="img/form_casa/4.jpg" alt="Festa de Casamento" class="min"></a></li>
                        </ul>
                        
                        <div class="lbox" id="format1">
                            <div class="box-img">
                                <a href="#format4" class="btn" id="prev">&#171;</a>
                                <a href="" class="btn" id="close">X</a>
                                <img src="img/form_casa/1.jpg" alt="Festa de Formatura">
                                <a href="#format2" class="btn" id="next">&#187;</a>
                            </div>
                        </div>
        
                        <div class="lbox" id="format2">
                            <div class="box-img">
                                <a href="#format1" class="btn" id="prev">&#171;</a>
                                <a href="" class="btn" id="close">X</a>
                                <img src="img/form_casa/2.jpg" alt="Festa de Formatura">
                                <a href="#format3" class="btn" id="next">&#187;</a>
                            </div>
                        </div>
        
                        <div class="lbox" id="format3">
                            <div class="box-img">
                                <a href="#format2" class="btn" id="prev">&#171;</a>
                                <a href="" class="btn" id="close">X</a>
                                <img src="img/form_casa/3.jpg" alt="Festa de Casamento">
                                <a href="#format4" class="btn" id="next">&#187;</a>
                            </div>
                        </div>
        
                        <div class="lbox" id="format4">
                            <div class="box-img">
                                <a href="#format3" class="btn" id="prev">&#171;</a>
                                <a href="" class="btn" id="close">X</a>
                                <img src="img/form_casa/4.jpg" alt="Festa de Casamento">
                                <a href="#format1" class="btn" id="next">&#187;</a>
                            </div>
                        </div>
                    </section>
                            
        </main>

MVC/RoleTopMVC/Views/Home/Index.cshtml
<main>
        <section id="historia">
            <div class="section-container">
                <div class="flex-group">
                    <h2><strong><em>Sobre</em></strong></h2>
                    <em>
                        <p>
                            Localizado na Santa Cecília, região central de São Paulo, o Rolê Top já está no mercado desde
                            2015, com
                            capacidade máxima de 400 pessoas, possui uma infra-estrutura completa para o seu evento,
                            incluindo ambiente
                            climatizado, banheiros (masculino e feminino), saídas de emergência, camarins, catracas, acessos
                            para
                            deficientes, câmeras de segurança e estacionamento no local.
                        </p><br>
                        <p>
                            O Rolê Top é o espaço de eventos que mais cresce em São Paulo, com a proposta de oferecer um
                            local acessível
                            para eventos corporativos, casamentos, aniversários, shows, desfiles, cerimônias, mostras de
                            cinema, festas
                            temáticas e outros tipos de eventos.
                        </p><br>
                        <p>
                            Entre em contato e veja como o Rolê Top torna o seu evento único, esperamos por você!
                        </p><br>
                        <h2><strong><em>A história</em></strong></h2>
                        <h3><em>de um espaço de eventos</em></h3><br>
                        <p>
                            Os sócios Cesar Sportore e Alexandre Fukaya foram os percussores na realização de eventos
                            fechados, onde o
                            cliente customiza sua festa.
                        </p><br>
                        <p>
                            Eles também são donos de uma hamburgueria e sempre conversando com seus clientes escutavam que
                            faltava um
                            local na região que realizasse eventos de todos os tipos e foi ai que tiveram a ideia de comprar
                            um galpão
                            e preparar o espaço para receber qualquer evento desde festas, formaturas, aniversários, casamentos,
                            cerimônias, etc.
                        </p>
                    </em>
                </div>
            </div>
        </section>

        <section id="infra">
                <div class="section-container">
                    <div class="infra-list">
                        <h2>Infraestrutura</h2>
                        <ul>
                            <li>Área Total: 150 x 40 m</li>
                            <li>Capacidade máxima: 400 pessoas</li>
                            <li>Máximo de 120 mesas</li>
                            <li>Ambiente climatizado</li>
                            <li>Camarins</li>
                            <li>Acesso para deficientes</li>
                            <li>Câmeras de segurança</li>
                            <li>Estacionamento no local</li>
                        </ul>
                    </div>
                    <img src="img/planta.jpg" alt="Planta do galpão" title="Planta do galpão" />
                </div>
            </section>

        <section id="local">
            <div class="section-container">
                <h3>Endereço</h3>
                <iframe
                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3657.8869961505543!2d-46.648477085071065!3d-23.53656648469522!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94ce5843deade6e3%3A0x124f377d06c7e71f!2sAlameda+Bar%C3%A3o+de+Limeira%2C+539+-+Campos+El%C3%ADseos%2C+S%C3%A3o+Paulo+-+SP%2C+01202-001!5e0!3m2!1sen!2sbr!4v1550223658410"
                    width="100%" height="100%" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
        </section>
    </main>

MVC/RoleTopMVC/Views/Serviços/Trabalhos.cshtml
<main>
            <section id="servicos">
                <div class="section-container">
                    <div class="flex-group">
                        <h2><strong><em>Serviço de Iluminação</em></strong></h2><br>
                        <em>
                            <p>
                                A iluminação qualificada é essencial para a um visual mais aconchegante e caloroso ao público do seu evento. 
                                Equipamentos, equipe técnica qualificada, processos de revisão e manutenções constantes fazem parte do
                                que garante que seu evento seja entregue como planejado com a locação de iluminação.
                            </p><br>
                            <p>
                                Conheça algumas das principais marcas que trabalhamos para locação de iluminação para shows:
                            </p><br>
                            <p>
                                - Avolites <br>
                                - American Pro <br>
                                - SGM <br>
                                - Star Litgh <br>
                                - Tec Led
                            </p><br>
                            <p>    
                                Além de refletores temos também outros itens como:
                            </p><br>
                            <p>
                                - Mesa de luz analógica <br>
                                - Mesa de luz digital <br>
                                - Moving Head Spot <br>
                                - Moving Head Wash led <br>
                                - Moving Led Spot <br>
                                - Refletor par led indoor <br>
                                - Refletor par led outdoor <br>
                                - Canhão de luz Seguidor. <br>
                                - Máquina de Fumaça <br>
                                - Luz led para buffet <br>
                                - Luz decorativa para mesa de jantar <br>
                                - Refletor de fachada
                            </p><br>
                            
                            <p>   
                                Valor: Sob consulta
                            </p><br>
                            <h2><strong><em>Serviço de Som</em></strong></h2><br>
                            <p>
                            Somos uma empresa especialista na realização de eventos e com vasta experiência no aluguel de sonorização.
                            </p><br>
                            <p>
                            Com mais de 25 anos de experiência no mercado de audiovisual, trabalhamos com as principais marcas do
                            mercado, como:
                            </p><br>
                            <p>
                            - DAS Audio, RCF;<br>
                            - Microfones Shure, Sennheiser, DPA e Coutryman;<br>
                            - Mesas de Som Yamaha, Allen Heath e AVID;<br>
                            </p><br>
                            <p>
                            Conheça nossos serviços para aluguel de sonorização:
                            </p><br>
                            <p>
                            - ÁUDIO <br>
                            - Sistemas de som <br>
                            - DJ’s <br>
                            - Sonorização mecânica <br>
                            - Captação de áudio <br>
                            - Tradução simultânea <br>
                            </p><br>
                            <p>
                            Valor: Sob consulta
                            </p><br>
                        </em>
                    </div>
                </div>
            </section>
        </main>

MVC/RoleTopMVC/Views/Shared/_HeaderHomePage.cshtml
<section id="fundo-galpao">
            <h1>Rolê Top</h1>
        </section>

MVC/RoleTopMVC/Views/Shared/_Layout.cshtml
@{
    var nomeView = (string) ViewData["NomeView"];
}

<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Rolê Top - Espaço de eventos, festas e casamentos</title>
    <link href="img/logo_roletop.png" rel="icon" type="image"/>
    <link href="https://fonts.googleapis.com/css?family=Crimson+Text:400,400i,700&display=swap" rel="stylesheet">
    <link href="~/css/style.css" rel="stylesheet" type="text/css">
    <script src="https://kit.fontawesome.com/349a64cb04.js"></script>
</head>

<body>
    <header>
        <nav>
            <div class="section-container">
                <img src="img/logo_roletop.png" alt="Logo Rolê Top" title="Logo Rolê Top">
                <ul>
                    <li id="bt-mobile-menu">
                        <a href="javascript:void(0);" class="icon" onclick="toggleMobileMenu()">
                            <i class="fa fa-bars"></i>
                        </a>
                    </li>
                    <li class="bt-common-menu"><a onclick="toggleMobileMenu()" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li class="bt-common-menu"><a onclick="toggleMobileMenu()" asp-controller="Eventos" asp-action="Shows">Eventos</a></li>
                    <li class="bt-common-menu"><a onclick="toggleMobileMenu()" asp-controller="Serviços" asp-action="Trabalhos">Serviços</a></li>
                    <li class="bt-common-menu"><a onclick="toggleMobileMenu()" asp-controller="Galeria" asp-action="Fotos">Fotos</a></li>
                    <li><a id="bt-faca_sua_reserva" href="contato.html">Faça sua reserva!</a></li>
                </ul>
            </div>
        </nav>
        @if("Home".Equals(nomeView))
        {
            Html.RenderPartial("_HeaderHomePage");
        }
    </header>
            @RenderBody()
    <footer>
        <div class="section-container">
            <address>
                Alameda Barão de Limeira, 539 - Santa Cecília, São Paulo - SP
            </address>
            <a href="duvidas.html">Dúvidas Frequentes</a>
            <a href="#">Voltar para o topo!</a>
        </div>
    </footer>

    <script>
        function toggleMobileMenu() {
            var ul = document.querySelector("nav ul");
            var commonButtons = document.querySelectorAll("nav .bt-common-menu");
            var icon = document.querySelector(".icon > i");

            ul.classList.toggle("mobile-mode");

            if (icon.classList.contains("fa-bars")) {
                icon.classList.remove("fa-bars");
                icon.classList.remove("fa");

                icon.classList.add("fas");
                icon.classList.add("fa-bolt");
            } else {
                icon.classList.remove("fas");
                icon.classList.remove("fa-bolt");

                icon.classList.add("fa");
                icon.classList.add("fa-bars");
            }

            for (var button of commonButtons) {
                button.classList.toggle("active");
            }

        }
        
    </script>
</body>

</html>